### ISSUE TITLE
Enhancement: Create VM with more than 1 NIC

### ISSUE THREAD

**Issue by tahiri-ahmed** [cloudfoundry-community/bosh-cloudstack-cpi-release#49]
Hi,

I need to plug two NICs in each deployed instance. I have declared two networks for the job in manifest as below:
```
networks:
  - name: bosh-first-net
    default: [dns, gateway]
    static_ips:
      - 10.234.250.109
  - name: bosh-second-net
    static_ips:
      - 10.77.111.254 
```

The deployment fails with this error:

> CPI error 'Bosh::Clouds::CpiError' with message 'java.lang.IllegalArgumentException: CPI currently supports at most 1 NIC per vm
CPI currently supports at most 1 NIC per vm
null' in 'create_vm' CPI method (00:00:03)
> Error 100: CPI error 'Bosh::Clouds::CpiError' with message 'java.lang.IllegalArgumentException: CPI currently supports at most 1 NIC per vm
CPI currently supports at most 1 NIC per vm
null' in 'create_vm' CPI method

As the error states, the feature of creating VM with more than one NIC is not implemented yet. Could you please put it in your roadmap?
